package com.example.shafaq.dineout;

import android.content.Context;
import android.os.Bundle;
import android.support.v7.app.AppCompatActivity;

import java.util.ArrayList;

/**
 * Class: Email Module
 * Generated BY: The one and only Shafaq Arshad
 * Purpose:sends Emails to Manager when he signs out at the end of the day
 * Precondition: The sales calculations are done and dusted and so is logic for finding type of report
 * Postcondition: Mail with sales pdf semt
 */
public class EmailActivity extends AppCompatActivity {

Context c=this;
    public static String DEST = "dailyReport.pdf";//temporaray storage of email
    public static String TypeOfReport= "Daily Sales Report";//Monthly, Daily, annulay
    public int numberOfColumns=5;
    public int[] columnWidths=new int[]{30 , 30,30 ,30 ,30};//width settng in px
    public String[] columnHeaders= new String[]{"DishName","Quantity","Actual Price","Sales","profit/Loss"};
    //
    private ArrayList<TableRow> trows= new ArrayList<TableRow>();//rows information and values
    private int[] Totals;//total field at the footer
    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        //Logic calculation by hasan here
        int typeOfreport=1;
        switch (typeOfreport){


            case 1://daily report
                DEST = "dailyReport.pdf";
                TypeOfReport= "Daily Sales Report";
                numberOfColumns=5;
                columnWidths=new int[]{30 , 30,30 ,30 ,30};

                columnHeaders= new String[]{"DishName","Quantity","Actual Price","Sales","profit/Loss"};
                TableRow r= new TableRow(new Object[]{"lasagna",1,1,1,1});

                trows.add(r);
                Totals=new int[]{123,234,345};//total sactual price sales, profit
                NestedTable.call(c,DEST,TypeOfReport,numberOfColumns,columnWidths,columnHeaders,trows,Totals);
                break;
            case 2://monthly
                DEST = "MonthlyReport.pdf";
                TypeOfReport= "Monthly Sales Report";
                numberOfColumns=4;
                columnWidths=new int[]{30 , 30,30 ,30};
                columnHeaders= new String[]{"Day","Sales","Expense","profit/Loss"};
                TableRow r1= new TableRow(new Object[]{"01/01/2018",1,1,1});

                trows.add(r1);

                Totals=new int[]{123,234,345};//total sactual price sales, profit

                NestedTable.call(c,DEST,TypeOfReport,numberOfColumns,columnWidths,columnHeaders,trows,Totals);
                break;
        }

        try {

            GMailSender sender = new GMailSender("dineoutx@gmail.com","ShafaqAirlines78");

            sender.addAttachment(c.getFilesDir()+"/files/"+DEST);

            sender.sendMail( TypeOfReport, "This mail has been sent from android app along with sales report...This is auto generated email please donnot reply",

                    "dineoutx@gmail.com",

                    "arshadshafaq15@gmail.com");






        } catch (Exception e) {

            System.out.println(e);

        }

    }
    }


