package com.example.shafaq.dineout;

/**
 * Created by shafaq on 12/1/2018.
 */

import java.io.ByteArrayInputStream;
import java.io.IOException;
import java.io.InputStream;
import java.io.OutputStream;
import java.security.Security;
import java.util.Properties;

import javax.activation.DataHandler;
import javax.activation.DataSource;
import javax.activation.FileDataSource;
import javax.mail.BodyPart;
import javax.mail.Message;
import javax.mail.Multipart;
import javax.mail.PasswordAuthentication;
import javax.mail.Session;
import javax.mail.Transport;
import javax.mail.internet.InternetAddress;
import javax.mail.internet.MimeBodyPart;
import javax.mail.internet.MimeMessage;
import javax.mail.internet.MimeMultipart;

/**
 * Class: Javax auto mail sender Module
 * Generated BY: The one and only Shafaq Arshad
 * Purpose:sends Emails using smtp
 * Precondition: The sales calculations are done and dusted and so is logic for finding type of report
 *
 * */
public class GMailSender extends javax.mail.Authenticator {

    private String mailhost = "smtp.gmail.com";

    private String user;

    private String password;

    private Session session;



    private Multipart _multipart = new MimeMultipart();

    static {

        Security.addProvider(new JSSEProvider());

    }



    public GMailSender(String user, String password) {

        this.user = "dineoutx@gmail.com";

        this.password = "ShafaqAirlines78";



        Properties props = new Properties();

        props.setProperty("mail.transport.protocol", "smtp");

        props.setProperty("mail.host", mailhost);

        props.put("mail.smtp.auth", "true");

        props.put("mail.smtp.port", "465");

        props.put("mail.smtp.socketFactory.port", "465");

        props.put("mail.smtp.socketFactory.class",

                "javax.net.ssl.SSLSocketFactory");

        props.put("mail.smtp.socketFactory.fallback", "false");

        props.setProperty("mail.smtp.quitwait", "false");



        session = Session.getDefaultInstance(props, this);

    }



    protected PasswordAuthentication getPasswordAuthentication() {

        return new PasswordAuthentication(user, password);

    }



    public synchronized void sendMail(final String subject1, final String body1,

                                     final String sender1,final String recipients1) throws Exception {
    new Thread(new Runnable() {
        String subject;
        String body;

        String sender;
        String recipients;
        {
            this.subject=subject1;
            this.body=body1;
            this.sender=sender1;
            this.recipients=recipients1;
        }
        @Override
        public void run() {
            try {

                MimeMessage message = new MimeMessage(session);

                DataHandler handler = new DataHandler(new ByteArrayDataSource(body.getBytes(), "text/plain"));

                message.setSender(new InternetAddress(sender));

                message.setSubject(subject);

                message.setDataHandler(handler);

                BodyPart messageBodyPart = new MimeBodyPart();

                messageBodyPart.setText(body);

                _multipart.addBodyPart(messageBodyPart);



                // Put parts in message

                message.setContent(_multipart);

                if (recipients.indexOf(',') > 0)

                    message.setRecipients(Message.RecipientType.TO,

                            InternetAddress.parse(recipients));

                else

                    message.setRecipient(Message.RecipientType.TO,

                            new InternetAddress(recipients));

                Transport.send(message);

            } catch (Exception e) {

                e.printStackTrace();
            }
        }
    }).start();


    }



    public void addAttachment(String filename) throws Exception {

        BodyPart messageBodyPart = new MimeBodyPart();

        DataSource source = new FileDataSource(filename);

        messageBodyPart.setDataHandler(new DataHandler(source));

        messageBodyPart.setFileName("SalesReport.pdf");



        _multipart.addBodyPart(messageBodyPart);

    }



    public class ByteArrayDataSource implements DataSource {

        private byte[] data;

        private String type;





        public ByteArrayDataSource(byte[] data, String type) {

            super();

            this.data = data;

            this.type = type;

        }



        public ByteArrayDataSource(byte[] data) {

            super();

            this.data = data;

        }





        public void setType(String type) {

            this.type = type;

        }



        public String getContentType() {

            if (type == null)

                return "application/octet-stream";

            else

                return type;

        }



        public InputStream getInputStream() throws IOException {

            return new ByteArrayInputStream(data);

        }



        public String getName() {

            return "ByteArrayDataSource";

        }



        public OutputStream getOutputStream() throws IOException {

            throw new IOException("Not Supported");

        }

    }

}