package com.example.shafaq.dineout;

/**
 * Created by shafaq on 12/1/2018.
 */

import java.security.AccessController;
import java.security.Provider;

/**
 * Class: JSEE provider Module
 * Generated BY: The one and only Shafaq Arshad
 * Purpose:does security things
 * DONT TOUCH IT OR ELSE YOU DIE!!!
 */

public final class JSSEProvider extends Provider {



    public JSSEProvider() {

        super("HarmonyJSSE", 1.0, "Harmony JSSE Provider");

        AccessController

                .doPrivileged(new java.security.PrivilegedAction<Void>() {

                    public Void run() {

                        put("SSLContext.TLS",

                                "org.apache.harmony.xnet.provider.jsse.SSLContextImpl");

                        put("Alg.Alias.SSLContext.TLSv1", "TLS");

                        put("KeyManagerFactory.X509",

                                "org.apache.harmony.xnet.provider.jsse.KeyManagerFactoryImpl");

                        put("TrustManagerFactory.X509",

                                "org.apache.harmony.xnet.provider.jsse.TrustManagerFactoryImpl");

                        return null;

                    }

                });

    }

}